name: Make Release
on:
  release:
    types:
      - created

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable
      - name: Build NeoVim
        run: nvim -u ./lua/plugins/init.lua --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
      - name: Compress NeoVim
        run: tar -zcvf neovim.tar.gz ./
      - name: Upload release files
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./neovim.tar.gz
          asset_name: neovim.tar.gz
          asset_content_type: application/gzip
